return {
  { "RishabhRD/nvim-lsputils", dependencies = { "RishabhRD/popfix" } },
  { "onsails/lspkind-nvim" },
  { "neovim/nvim-lspconfig" },
  { "danro/rename.vim" },
  { "tpope/vim-endwise" },
  { "tpope/vim-repeat" },
  { "supercollider/scvim" },
  { "folke/lsp-colors.nvim" },
  { "nvim-lua/plenary.nvim" },
  { "antoinemadec/FixCursorHold.nvim" },
  { "kosayoda/nvim-lightbulb" },
  { "ray-x/guihua.lua", build = "cd lua/fzy && make" },
  { "ray-x/navigator.lua" },
  { "github/copilot.vim" },
  { "machakann/vim-sandwich", event = { "BufReadPost", "BufNewFile" }},
}
