return {
	"nvim-treesitter/nvim-treesitter",
	branch = "main",
	build = ":TSUpdate",
	dependencies = {
		"nvim-treesitter/nvim-treesitter-textobjects",
	},
	config = function()
		require("nvim-treesitter").setup()

		local ensure_installed = {
			"bash",
			"c",
			"cpp",
			"css",
			"csv",
			"diff",
			"dockerfile",
			"elixir",
			"erlang",
			"fish",
			"git_config",
			"git_rebase",
			"gitattributes",
			"gitcommit",
			"gitignore",
			"go",
			"gomod",
			"gosum",
			"gowork",
			"gotmpl",
			"graphql",
			"haskell",
			"html",
			"javascript",
			"jq",
			"jsdoc",
			"json",
			"latex",
			"lua",
			"luadoc",
			"markdown",
			"markdown_inline",
			"python",
			"regex",
			"ruby",
			"rust",
			"scss",
			"sql",
			"ssh_config",
			"supercollider",
			"svelte",
			"tmux",
			"toml",
			"tsx",
			"typescript",
			"typst",
			"vim",
			"vimdoc",
			"vue",
			"yaml",
			"zig",
		}

		require("nvim-treesitter").install(ensure_installed)
	end,
}
