return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	event = { "BufReadPost", "BufNewFile" },
	config = function()
		require("nvim-treesitter.configs").setup({
			highlight = { enable = true },
			indent = { enable = true, disable = { "python" } },
			context_commentstring = { enable = true, enable_autocmd = false },
			ensure_installed = {
				"bash",
        "c",
        "cpp",
				"css",
        "csv",
        "diff",
				"dockerfile",
        "elixir",
        "erlang",
				"fish",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
				"go",
        "gomod",
        "gosum",
        "gowork",
        "gotmpl",
				"graphql",
        "haskell",
				"html",
				"javascript",
        "jq",
				"jsdoc",
				"json",
				"lua",
        "luadoc",
        "markdown",
        "markdown_inline",
				"python",
        "regex",
				"ruby",
				"rust",
				"scss",
        "sql",
        "ssh_config",
				"supercollider",
        "tmux",
        "toml",
				"tsx",
				"typescript",
				"vim",
        "vue",
        "yaml",
        "zig",
			},
			auto_install = true,
			sync_install = false,
			ignore_install = {},
			modules = {},
			incremental_selection = {
				enable = true,
				keymaps = {
					init_selection = "gnn",
					node_incremental = "gnn",
					scope_incremental = "gnc",
					node_decremental = "gnd",
				},
			},
		})
	end,
}
