return {
	"folke/which-key.nvim",
	dependencies = {
		"echasnovski/mini.icons",
		"nvim-tree/nvim-web-devicons",
	},
	event = "VeryLazy",
	config = function()
		local wk = require("which-key")
		wk.setup({ preset = "helix" })
		wk.add({
			{ "<leader><C-K>", hidden = true },
			{ "<leader><space>", group = "Diagnostics" },
			{ "<leader><space>D", desc = "Show definition", icon = "󰈇" },
			{ "<leader><space>H", desc = "Toggle inlay hints", icon = "󰌵" },
			{ "<leader><space>R", desc = "Rename", icon = "󰑕" },
			{ "<leader><space>S", desc = "Show signature help", icon = "󰷣" },
			{ "<leader><space>a", desc = "Show code actions", icon = "󰌵" },
			{ "<leader><space>c", desc = "Show declaration", icon = "󰈇" },
			{ "<leader><space>d", desc = "Show diagnostics", icon = "󰅚" },
			{ "<leader><space>h", desc = "Show hover", icon = "󰆷" },
			{ "<leader><space>i", desc = "Show implementation", icon = "󰈇" },
			{ "<leader><space>r", desc = "Show references", icon = "󰈇" },
			{ "<leader>P", hidden = true },
			{ "<leader>S", desc = "Search & Replace (Flash)", icon = "⚡" },
			{ "<leader>_", group = "Comments" },
			{ "<leader>w", desc = "Save", icon = "" },
			{ "<leader>q", desc = "Quit" },
			{ "<leader>a", desc = "Dashboard & Outline", icon = "󱥈" },
			{ "<leader>aA", desc = "Dashboard", icon = "󱥈" },
			{ "<leader>c", group = "Copilot & Path", icon = " " },
			{ "<leader>cc", desc = "Copilot Chat", icon = "" },
			{ "<leader>cf", desc = "Copy full path", icon = "" },
			{ "<leader>cs", desc = "Copilot Status", icon = "" },
			{ "<leader>cp", desc = "Copilot Panel", icon = "" },
			{ "<leader>cr", desc = "Copy relative path", icon = "" },
			{ "<leader>f", group = "Finding & Format" },
			{ "<leader>fb", desc = "Buffers", icon = "󰈯" },
			{ "<leader>ff", desc = "Files", icon = "󰈞" },
			{ "<leader>fG", desc = "Git Status", icon = "󰊢" },
			{ "<leader>fr", desc = "References", icon = "󰈇" },
			{ "<leader>fd", desc = "Definitions", icon = "󰈇" },
			{ "<leader>fg", desc = "Search (grep)", icon = "" },
			{ "<leader>fh", desc = "Help", icon = "󰋖" },
			{ "<leader>fm", group = "Format", icon = "󰉼" },
			{ "<leader>ft", desc = "Todo Comments", icon = "☑" },
			{ "<leader>fz", group = "fzf", icon = "" },
			{ "<leader>fzb", desc = "Buffers", icon = "󰈯" },
			{ "<leader>fzf", desc = "Frecency", icon = "󰋚" },
			{ "<leader>fzF", desc = "Files", icon = "󰈞" },
			{ "<leader>fzg", desc = "Live Grep", icon = "" },
			{ "<leader>fzG", desc = "Git Status", icon = "󰊢" },
			{ "<leader>fzk", desc = "Keymaps", icon = "󰌋" },
			{ "<leader>fzo", desc = "Old Files", icon = "󰋚" },
			{ "<leader>fzq", desc = "Quickfix", icon = "󰁨" },
			{ "<leader>fzr", desc = "Resume", icon = "" },
			{ "<leader>fzu", desc = "Undotree", icon = "󰕌" },
			{ "<leader>fzz", desc = "Global", icon = "󰈇" },
			{ "<leader>fzl", group = "LSP", icon = "" },
			{ "<leader>fzlc", desc = "Declarations", icon = "󰈇" },
			{ "<leader>fzlD", desc = "Definitions", icon = "󰈇" },
			{ "<leader>fzlr", desc = "References", icon = "󰈇" },
			{ "<leader>fzlt", desc = "Type Definitions", icon = "󰈇" },
			{ "<leader>fmt", desc = "Format [LSP]" },
			{ "<leader>fn", desc = "Notify" },
			{ "<leader>g", group = "Git" },
			{ "<leader>gL", desc = "LazyGit", icon = "" },
			{ "<leader>gR", desc = "Reset buffer", icon = "" },
			{ "<leader>gS", desc = "Stage buffer", icon = "" },
			{ "<leader>gU", desc = "Reset buffer index", icon = "" },
			{ "<leader>gb", desc = "Toggle Line Blame", icon = "󰊢" },
			{ "<leader>gc", desc = "Commit", icon = "" },
			{ "<leader>gh", desc = "Line highlight", icon = "󰘤" },
			{ "<leader>gj", desc = "Next hunk", icon = "󰒭" },
			{ "<leader>gk", desc = "Previous hunk", icon = "󰒮" },
			{ "<leader>gl", desc = "Toggle number highlight", icon = "󰘤" },
			{ "<leader>gp", desc = "Preview hunk", icon = "󰆷" },
			{ "<leader>gr", desc = "Reset hunk", icon = "" },
			{ "<leader>gs", desc = "Stage hunk", icon = "󰆓" },
			{ "<leader>gu", desc = "Undo stage hunk", icon = "" },
			{ "<leader>h", group = "Git signs" },
			{ "<leader>k", hidden = true },
			{ "<leader>l", group = "Lensline", icon = "󰍉" },
			{ "<leader>ll", desc = "Show Lensline", icon = "󰍉" },
			{ "<leader>lh", desc = "Hide Lensline", icon = "󰍉" },
			{ "<leader>lp", desc = "Switch Lensline profile", icon = "󰍉" },
			{ "<leader>n", group = "Line numbering", icon = "󰉻" },
			{ "<leader>nh", desc = "No highlight", icon = "" },
			{ "<leader>no", desc = "No line numbers", icon = "󰉻" },
			{ "<leader>nr", group = "Relative line numbering", icon = "󰉻" },
			{ "<leader>nrr", desc = "No relative line numbering", icon = "󰉻" },
			{ "<leader>nu", desc = "Line numbers", icon = "󰉻" },
			{ "<leader>p", hidden = true },
			{ "<leader>r", group = "Relative line numbering", icon = "󰉻" },
			{ "<leader>rn", desc = "Relative line numbering", icon = "󰉻" },
			{ "<leader>s", desc = "Session, Source, and Split", icon = "󰆓" },
			{ "<leader>sh", desc = "Split Horizontal", icon = "󰝘" },
			{ "<leader>sp", desc = "Split Horizontal", icon = "󰝘" },
			{ "<leader>sv", desc = "Split Vertical", icon = "󰝗" },
			{ "<leader>sH", desc = "Move Split Left", icon = "" },
			{ "<leader>sJ", desc = "Move Split Down", icon = "" },
			{ "<leader>sK", desc = "Move Split Up", icon = "" },
			{ "<leader>sL", desc = "Move Split Right", icon = "" },
			{ "<leader>se", desc = "Equalize Splits", icon = "󰖯" },
			{ "<leader>sx", desc = "Close Split", icon = "󰅖" },
			{ "<leader>ss", desc = "Start/Stop Session", icon = "󰑋" },
			{ "<leader>sr", desc = "Restore Session", icon = "" },
			{ "<leader>sw", desc = "Swap With Next", icon = "󰒺" },
			{ "<leader>sr", desc = "Rotate Splits Clockwise", icon = "↻" },
			{ "<leader>sR", desc = "Rotate Splits Anti-Clockwise", icon = "↺" },
			{ "<leader>t", group = "Testing & Tree" },
			{ "<leader>tF", desc = "Neo-tree Filesystem", icon = "󰉓" },
			{ "<leader>tb", desc = "Neo-tree Buffers", icon = "󰉋" },
			{ "<leader>tf", desc = "Test file", icon = "󰈔" },
			{ "<leader>tg", desc = "Toggle Neo-tree", icon = "󰙅" },
			{ "<leader>tl", desc = "Test last", icon = "󰒭" },
			{ "<leader>tn", desc = "Test nearest", icon = "󰛣" },
			{ "<leader>ts", desc = "Test suite", icon = "󱞊" },
			{ "<leader>tt", desc = "Trouble", icon = "󰙅" },
			{ "<leader>tv", desc = "Test visit", icon = "󰆷" },
			{ "<leader>u", desc = "Undo tree", icon = "󰕌" },
			{ "<leader><space>5", desc = "Continue", icon = "" },
			{ "<leader><space>0", desc = "Step over", icon = "" },
			{ "<leader><space>1", desc = "Step into", icon = "󰆹" },
			{ "<leader><space>2", desc = "Step out", icon = "" },
			{ "<Leader><space>b", desc = "Toggle breakpoint", icon = "󰃤" },
			{ "<Leader><space>B", desc = "Set breakpoint", icon = "󰃤" },
			{ "<Leader><space>pr", desc = "Open REPL", icon = "" },
			{ "<Leader><space>pl", desc = "Run last", icon = "󰘁" },
			{ "<Leader><space>p", desc = "More DAP" },
		})
	end,
}
