return {
	"folke/which-key.nvim",
  dependencies = {
    "echasnovski/mini.icons",
    "nvim-tree/nvim-web-devicons"
  },
	event = "VeryLazy",
	config = function()
		local wk = require("which-key")
    wk.setup({preset = "helix"})
    wk.add(
      {
        { "<leader><C-K>", hidden = true },
        { "<leader><space>", group = "Diagnostics" },
        { "<leader><space>P", desc = "Rename" },
        { "<leader>P", hidden = true },
        { "<leader>S", desc = "Search & Replace" },
        { "<leader>_", group = "Comments" },
        { "<leader>w", desc = "Save", icon="" },
        { "<leader>q", desc = "Quit" },
        { "<leader>a", desc = "Dashboard & Outline", icon="󱥈"},
        { "<leader>aA", desc = "Alpha Dashboard", icon="󱥈"},
        { "<leader>c", group = "Copilot & Path", icon=" "},
        { "<leader>cc", desc = "Copilot Chat", icon="" },
        { "<leader>cf", desc = "Copy full path", icon="" },
        { "<leader>cp", desc = "Copilot Panel", icon="" },
        { "<leader>f", group = "Finding & Format" },
        { "<leader>fb", desc = "Buffers" },
        { "<leader>ff", desc = "Files" },
        { "<leader>fr", desc = "References" },
        { "<leader>fd", desc = "Declarations" },
        { "<leader>fg", desc = "Search (grep)" },
        { "<leader>fh", desc = "Help", icon="󰋖" },
        { "<leader>fm", group = "Format" },
        { "<Leader>fz", group = "fzf" },
        { "<Leader>fzl", group = "LSP" },
        { "<leader>fmt", desc = "Format [LSP]" },
        { "<leader>fn", desc = "Notify" },
        { "<leader>g", group = "Git" },
        { "<leader>gR", desc = "Reset buffer" },
        { "<leader>gS", desc = "Stage buffer" },
        { "<leader>gU", desc = "Reset buffer index" },
        { "<leader>gb", desc = "Toggle Line Blame" },
        { "<leader>gc", desc = "Commit", icon="" },
        { "<leader>gh", desc = "Line highlight", icon="󰘤" },
        { "<leader>gj", desc = "Next hunk", icon="" },
        { "<leader>gk", desc = "Previous hunk", icon="" },
        { "<leader>gl", desc = "Line highlight", icon="󰘤" },
        { "<leader>gp", desc = "Preview hunk", icon="" },
        { "<leader>gr", desc = "Reset hunk", icon="" },
        { "<leader>gs", desc = "Stage hunk", icon="" },
        { "<leader>gu", desc = "Undo stage hunk", icon="" },
        { "<leader>h", group = "Git signs" },
        { "<leader>k", hidden = true },
        { "<leader>n", group = "Line numbering", icon="󰉻" },
        { "<leader>nh", desc = "No highlight", icon="" },
        { "<leader>no", desc = "No line numbers", icon="󰉻" },
        { "<leader>nr", group = "Relative line numbering", icon="󰉻" },
        { "<leader>nrr", desc = "No relative line numbering", icon="󰉻" },
        { "<leader>nu", desc = "Line numbers", icon="󰉻" },
        { "<leader>p", hidden = true },
        { "<leader>r", group = "Relative line numbering", icon="󰉻" },
        { "<leader>rn", desc = "Relative line numbering", icon="󰉻" },
        { "<leader>s", desc = "Session, Source, and Split" },
        { "<leader>t", group = "Testing & Tree" },
        { "<leader>tf", desc = "Test file", icon="󰈔" },
        { "<leader>tl", desc = "Test last" },
        { "<leader>tn", desc = "Test nearest" },
        { "<leader>ts", desc = "Test suite", icon="󱞊" },
        { "<leader>tt", desc = "Trouble", icon="󰙅" },
        { "<leader>tv", desc = "Test visit" },
        { "<leader><space>5", desc = "Continue", icon="" },
        { "<leader><space>0", desc = "Step over", icon="" },
        { "<leader><space>1", desc = "Step into", icon="󰆹" },
        { "<leader><space>2", desc = "Step out", icon="" },
        { "<Leader><space>b", desc = "Toggle breakpoint", icon="󰃤" },
        { "<Leader><space>B", desc = "Set breakpoint", icon="󰃤" },
        { "<Leader><space>pr",desc = "Open REPL", icon="" },
        { "<Leader><space>pl", desc = "Run last", icon="󰘁" },
        { "<Leader><space>p", desc = "More DAP" },
      }
    )
	end,
}
