---
on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - "**/*.toml"
  pull_request:
    paths:
      - "**/*.toml"

jobs:
  tomllint:
    name: Lint TOML Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install tomllint
        run: pip install tomllint
      - name: Run tomllint on each TOML file
        run: |
          set -euo pipefail
          shopt -s globstar
          found=false
          for f in **/*.toml; do
            if [ -f "$f" ]; then
              found=true
              echo "==> Linting $f"
              tomllint "$f"
            fi
          done
          if [ "$found" = false ]; then
            echo "No .toml files found; skipping."
          fi

  toml_lint_tree_sitter:
    name: Lint TOML with yaegassy/toml-lint
    runs-on: ubuntu-latest
    needs: tomllint
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install toml-lint (yaegassy)
        run: cargo install toml-lint
      - name: Run toml-lint
        run: toml-lint .
